version: '3'

services:
  dojo-postgres:
    image: postgres
    environment:
      POSTGRES_PASSWORD: "Dojo2021!"
    ports:
      - "25432:5432"
    volumes:
      - /temp/DojoSQL:/var/lib/postgresql/data 
    networks:
      - dojo-network
      
  dojo-pgadmin-compose:
    image: dpage/pgadmin4
    environment:
      PGADMIN_DEFAULT_EMAIL: "dojo@dojo.com.br"
      PGADMIN_DEFAULT_PASSWORD: "Dojo2021!"
    ports:
      - "7777:80"
    depends_on:
      - dojo-postgres
    networks:
      - dojo-network

networks: 
  dojo-network:
    driver: bridge   